// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4Roou4pmLYG6IqQ_oh2rmCDWPOGPDjEM',
    appId: '1:704948617465:web:449acd0ab6e761143aa228',
    messagingSenderId: '704948617465',
    projectId: 'flutter-e4ea0',
    authDomain: 'flutter-e4ea0.firebaseapp.com',
    storageBucket: 'flutter-e4ea0.appspot.com',
    measurementId: 'G-3J884JTLSV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdrBAUWvExgG-kYumnjqm48P-HiDso7u8',
    appId: '1:704948617465:android:5c9eb6924ad803e03aa228',
    messagingSenderId: '704948617465',
    projectId: 'flutter-e4ea0',
    storageBucket: 'flutter-e4ea0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxaCB3cVlBWce5740dbrdltj6IxWXtXI0',
    appId: '1:704948617465:ios:004eb39afca19b513aa228',
    messagingSenderId: '704948617465',
    projectId: 'flutter-e4ea0',
    storageBucket: 'flutter-e4ea0.appspot.com',
    iosBundleId: 'com.alltechsavvy.flutterFirebaseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxaCB3cVlBWce5740dbrdltj6IxWXtXI0',
    appId: '1:704948617465:ios:004eb39afca19b513aa228',
    messagingSenderId: '704948617465',
    projectId: 'flutter-e4ea0',
    storageBucket: 'flutter-e4ea0.appspot.com',
    iosBundleId: 'com.alltechsavvy.flutterFirebaseApp',
  );
}
